[settings]
ticker = auto
Max_positions = 3
initial_direction = Sell     ; Buy or Sell
base_order_size = 20
volume_scale = 1.5
breakeven_threshold_pct = -4
stop_loss_pct = 0.25    ;2
increment_pct = 1.5
take_profit_pct = 1  ;8
sma_period = 200
hma1_period = 40
hma2_period = 60
hma3_period = 80
sma_timeframe = 0
hma1_timeframe = 1H
hma2_timeframe = 4H
hma3_timeframe = 1D

[telegram]
; api_token = 7336700820:AAG3EgR4KTOWh4oXwsB6JMJhrnCQCilI8vg
api_token = 7796717794:AAGVZdh3E4uTsI1-9F5UCbJ6bo0r98Iab98
; channel_chat_id_1 = 214780750
; channel_chat_id_2 = 6043578307
channel_chat_id_1 = 7215735113
channel_chat_id_2 = 7725197424

[binance]
; api_key = NsZZx2NTAcEjyaATuZVYtWX3lk1mejZOnXU68TjIWBTazjWeAHvQJBlD4okSq61t
api_key = EOerjL7Cq9Fyeh1fdeg0WqGcfE7wXwOnvlKUYPrLn8TfzeKUlMMtunGg0d2kmvQo
api_secret = rvepMkv1LxAqtXevQBxw9xuOs05vDmjMa2E66iGPDJCoWsgxOSzYYst716SZVrvv

test_api_key = kcMAZgbMvGlU4DSXpU0xgOt8PrgZ2LLpjdoDAvuZyQEd99ibmhGJz4BSYdcjuAa5
test_api_secret = 63ycOPCtMFmOD9QMd35nub20Ep1bzDOVozZ75csQWtWf1cvUHfrHdqv9TVbfWv3H